//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MVC.ServiceReference1.CompositeType GetDataUsingDataContract(MVC.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MVC.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(MVC.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        ApplicationService.DTOs.CategoryDTO[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.CategoryDTO[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCategory", ReplyAction="http://tempuri.org/IService1/PostCategoryResponse")]
        string PostCategory(ApplicationService.DTOs.CategoryDTO categoryDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCategory", ReplyAction="http://tempuri.org/IService1/PostCategoryResponse")]
        System.Threading.Tasks.Task<string> PostCategoryAsync(ApplicationService.DTOs.CategoryDTO categoryDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutCategory", ReplyAction="http://tempuri.org/IService1/PutCategoryResponse")]
        string PutCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutCategory", ReplyAction="http://tempuri.org/IService1/PutCategoryResponse")]
        System.Threading.Tasks.Task<string> PutCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoryById", ReplyAction="http://tempuri.org/IService1/GetCategoryByIdResponse")]
        ApplicationService.DTOs.CategoryDTO GetCategoryById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoryById", ReplyAction="http://tempuri.org/IService1/GetCategoryByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.CategoryDTO> GetCategoryByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        string DeleteCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        System.Threading.Tasks.Task<string> DeleteCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGames", ReplyAction="http://tempuri.org/IService1/GetGamesResponse")]
        ApplicationService.DTOs.GameDTO[] GetGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGames", ReplyAction="http://tempuri.org/IService1/GetGamesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO[]> GetGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostGame", ReplyAction="http://tempuri.org/IService1/PostGameResponse")]
        string PostGame(ApplicationService.DTOs.GameDTO gameDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostGame", ReplyAction="http://tempuri.org/IService1/PostGameResponse")]
        System.Threading.Tasks.Task<string> PostGameAsync(ApplicationService.DTOs.GameDTO gameDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutGame", ReplyAction="http://tempuri.org/IService1/PutGameResponse")]
        string PutGame(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutGame", ReplyAction="http://tempuri.org/IService1/PutGameResponse")]
        System.Threading.Tasks.Task<string> PutGameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGameById", ReplyAction="http://tempuri.org/IService1/GetGameByIdResponse")]
        ApplicationService.DTOs.GameDTO GetGameById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGameById", ReplyAction="http://tempuri.org/IService1/GetGameByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO> GetGameByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGame", ReplyAction="http://tempuri.org/IService1/DeleteGameResponse")]
        string DeleteGame(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGame", ReplyAction="http://tempuri.org/IService1/DeleteGameResponse")]
        System.Threading.Tasks.Task<string> DeleteGameAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MVC.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MVC.ServiceReference1.IService1>, MVC.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MVC.ServiceReference1.CompositeType GetDataUsingDataContract(MVC.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(MVC.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ApplicationService.DTOs.CategoryDTO[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.CategoryDTO[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public string PostCategory(ApplicationService.DTOs.CategoryDTO categoryDTO) {
            return base.Channel.PostCategory(categoryDTO);
        }
        
        public System.Threading.Tasks.Task<string> PostCategoryAsync(ApplicationService.DTOs.CategoryDTO categoryDTO) {
            return base.Channel.PostCategoryAsync(categoryDTO);
        }
        
        public string PutCategory(int id) {
            return base.Channel.PutCategory(id);
        }
        
        public System.Threading.Tasks.Task<string> PutCategoryAsync(int id) {
            return base.Channel.PutCategoryAsync(id);
        }
        
        public ApplicationService.DTOs.CategoryDTO GetCategoryById(int id) {
            return base.Channel.GetCategoryById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.CategoryDTO> GetCategoryByIdAsync(int id) {
            return base.Channel.GetCategoryByIdAsync(id);
        }
        
        public string DeleteCategory(int id) {
            return base.Channel.DeleteCategory(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCategoryAsync(int id) {
            return base.Channel.DeleteCategoryAsync(id);
        }
        
        public ApplicationService.DTOs.GameDTO[] GetGames() {
            return base.Channel.GetGames();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO[]> GetGamesAsync() {
            return base.Channel.GetGamesAsync();
        }
        
        public string PostGame(ApplicationService.DTOs.GameDTO gameDTO) {
            return base.Channel.PostGame(gameDTO);
        }
        
        public System.Threading.Tasks.Task<string> PostGameAsync(ApplicationService.DTOs.GameDTO gameDTO) {
            return base.Channel.PostGameAsync(gameDTO);
        }
        
        public string PutGame(int id) {
            return base.Channel.PutGame(id);
        }
        
        public System.Threading.Tasks.Task<string> PutGameAsync(int id) {
            return base.Channel.PutGameAsync(id);
        }
        
        public ApplicationService.DTOs.GameDTO GetGameById(int id) {
            return base.Channel.GetGameById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO> GetGameByIdAsync(int id) {
            return base.Channel.GetGameByIdAsync(id);
        }
        
        public string DeleteGame(int id) {
            return base.Channel.DeleteGame(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteGameAsync(int id) {
            return base.Channel.DeleteGameAsync(id);
        }
    }
}
